// SPDX-FileCopyrightText: 2025 CrazeTheDragon <drago.felcon@gmail.com>
// 
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Guidebook.Richtext;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Client._Pirate.Changelog;

// using Content.Client.Changelog;
// using Content.Client.Resources;
// using static Content.Client.Changelog.ChangelogManager;

namespace Content.Client._Pirate.Changelog;

[GenerateTypedNameReferences]

public sealed partial class PirateChangelogTab : Control
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly PirateChangelogManager _changelogManager = default!;

    public PirateChangelogTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void PopulateChangelog(PirateChangelog changelog)
    {
        var byDay = changelog.Entries.GroupBy(e => e.Time.ToLocalTime().Date).OrderByDescending(c => c.Key);
        // var hasRead = changelog.Name != MainChangelogName || _changelog.MaxId <= _changelog.LastReadId;

        foreach (var dayEntries in byDay)
        {
            var day = dayEntries.Key;
            string dayTemp;

            if (day == DateTime.Today)
            {
                dayTemp = Loc.GetString("changelog-today");
            }
            else if (day == DateTime.Today.AddDays(-1))
            {
                dayTemp = Loc.GetString("changelog-yesterday");
            }
            else
            {
                dayTemp = day.ToShortDateString();
            }

            ChangelogBody.AddChild(new Label
            {
                Text = dayTemp,
                StyleClasses = { StyleBase.StyleClassLabelHeading },
                Margin = new Thickness(4, 6, 0, 0)
            });
            foreach (var entry in dayEntries)
            {
                var authorLabel = new RichTextLabel
                {
                    Margin = new Thickness(6, 0, 0, 0)
                };

                authorLabel.SetMessage(
                    FormattedMessage.FromMarkupOrThrow(
                        Loc.GetString("changelog-author-changed",
                        ("author", FormattedMessage.EscapeText(entry.Author)))
                    )
                );
                ChangelogBody.AddChild(authorLabel);

                foreach (var change in entry.Changes)
                {
                    var text = new RichTextLabel();

                    text.SetMessage(FormattedMessage.FromUnformatted(change.Message));
                    ChangelogBody.AddChild(new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        Margin = new Thickness(14, 1, 10, 2),
                        Children =
                        {
                            GetIcon(change.Type),
                            text
                        }
                    });
                }
            }
        }
    }

    private TextureRect GetIcon(PirateChangelogLineType type)
    {
        var (file, color) = type switch
        {
            PirateChangelogLineType.Add => ("plus.svg.192dpi.png", "#6ED18D"),
            PirateChangelogLineType.Remove => ("minus.svg.192dpi.png", "#D16E6E"),
            PirateChangelogLineType.Fix => ("bug.svg.192dpi.png", "#D1BA6E"),
            PirateChangelogLineType.Tweak => ("wrench.svg.192dpi.png", "#6E96D1"),
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
        };

        return new TextureRect
        {
            Texture = _resourceCache.GetTexture(new ResPath($"/Textures/Interface/Changelog/{file}")),
            VerticalAlignment = VAlignment.Top,
            TextureScale = new Vector2(0.5f, 0.5f),
            Margin = new Thickness(2, 4, 6, 2),
            ModulateSelfOverride = Color.FromHex(color)
        };
    }
}
